import type { Tutor, Session, Review } from '../types'

const tutorAvatars = [
  'https://api.dicebear.com/9.x/notionists/svg?seed=James',
  'https://api.dicebear.com/9.x/notionists/svg?seed=Sarah',
  'https://api.dicebear.com/9.x/notionists/svg?seed=Wei',
  'https://api.dicebear.com/9.x/notionists/svg?seed=Priya',
  'https://api.dicebear.com/9.x/notionists/svg?seed=Ahmad',
  'https://api.dicebear.com/9.x/notionists/svg?seed=Mei',
  'https://api.dicebear.com/9.x/notionists/svg?seed=Raj',
  'https://api.dicebear.com/9.x/notionists/svg?seed=Lily',
]

const studentAvatars = [
  'https://api.dicebear.com/9.x/notionists/svg?seed=Alex',
  'https://api.dicebear.com/9.x/notionists/svg?seed=Bella',
  'https://api.dicebear.com/9.x/notionists/svg?seed=Chen',
  'https://api.dicebear.com/9.x/notionists/svg?seed=Devi',
]

export const mockTutors: Tutor[] = [
  {
    id: 't1',
    clerkId: 'clerk_t1',
    name: 'James Tan',
    email: 'james.tan@edu.sg',
    avatar: tutorAvatars[0],
    bio: 'Former MOE teacher with 12 years of experience teaching O-Level and A-Level Mathematics. I believe every student can excel with the right guidance and structured practice.',
    qualifications: ['NUS BSc Mathematics (Honours)', 'NIE PGDE', 'MOE Registered Teacher'],
    subjects: [
      { name: 'Mathematics', level: 'O-Level' },
      { name: 'Mathematics', level: 'A-Level' },
      { name: 'Further Mathematics', level: 'A-Level' },
    ],
    hourlyRate: 65,
    rating: 4.9,
    totalReviews: 127,
    totalSessions: 340,
    teachingStyle: 'Structured and methodical. I focus on building strong fundamentals before tackling complex problems. Lots of practice questions and exam strategies.',
    verified: true,
    joinedAt: '2023-03-15',
  },
  {
    id: 't2',
    clerkId: 'clerk_t2',
    name: 'Sarah Lim',
    email: 'sarah.lim@edu.sg',
    avatar: tutorAvatars[1],
    bio: 'Passionate Chemistry tutor specializing in A-Level and IB Chemistry. NTU Chemistry graduate with a knack for making complex concepts simple and fun.',
    qualifications: ['NTU BSc Chemistry (First Class)', 'Cambridge CELTA', '8 Years Tutoring Experience'],
    subjects: [
      { name: 'Chemistry', level: 'O-Level' },
      { name: 'Chemistry', level: 'A-Level' },
      { name: 'Chemistry', level: 'IB' },
    ],
    hourlyRate: 70,
    rating: 4.8,
    totalReviews: 98,
    totalSessions: 265,
    teachingStyle: 'Interactive and visual. I use animations, models, and real-world examples to explain abstract chemistry concepts. Regular quizzes to reinforce learning.',
    verified: true,
    joinedAt: '2023-06-01',
  },
  {
    id: 't3',
    clerkId: 'clerk_t3',
    name: 'Wei Ming Chen',
    email: 'weiming@edu.sg',
    avatar: tutorAvatars[2],
    bio: 'Full-time Physics tutor with a track record of helping students jump 2-3 grades. Specializing in O-Level and A-Level Physics with real-world applications.',
    qualifications: ['NUS BSc Physics', 'MOE Teaching Award 2021', '10 Years Experience'],
    subjects: [
      { name: 'Physics', level: 'O-Level' },
      { name: 'Physics', level: 'A-Level' },
    ],
    hourlyRate: 60,
    rating: 4.7,
    totalReviews: 85,
    totalSessions: 210,
    teachingStyle: 'Hands-on and experiment-driven. I connect physics theory to everyday phenomena so students truly understand rather than memorize.',
    verified: true,
    joinedAt: '2023-01-20',
  },
  {
    id: 't4',
    clerkId: 'clerk_t4',
    name: 'Priya Sharma',
    email: 'priya.s@edu.sg',
    avatar: tutorAvatars[3],
    bio: 'English Language and Literature specialist. Cambridge-trained with extensive experience in GCE O-Level and A-Level English. Strong focus on essay writing and comprehension skills.',
    qualifications: ['Cambridge MA English Literature', 'TESOL Certified', '6 Years Experience'],
    subjects: [
      { name: 'English Language', level: 'O-Level' },
      { name: 'English Literature', level: 'O-Level' },
      { name: 'General Paper', level: 'A-Level' },
    ],
    hourlyRate: 55,
    rating: 4.9,
    totalReviews: 112,
    totalSessions: 290,
    teachingStyle: 'Discussion-based learning with a focus on critical thinking. I help students develop their unique voice while mastering exam techniques.',
    verified: true,
    joinedAt: '2023-04-10',
  },
  {
    id: 't5',
    clerkId: 'clerk_t5',
    name: 'Ahmad Razak',
    email: 'ahmad.r@edu.sg',
    avatar: tutorAvatars[4],
    bio: 'Computing and Mathematics tutor with industry experience at Google. I teach programming concepts alongside mathematical thinking for the digital age.',
    qualifications: ['SMU BSc Information Systems', 'Google Certified Educator', 'AWS Cloud Practitioner'],
    subjects: [
      { name: 'Computing', level: 'O-Level' },
      { name: 'Computing', level: 'A-Level' },
      { name: 'Mathematics', level: 'O-Level' },
    ],
    hourlyRate: 75,
    rating: 4.8,
    totalReviews: 64,
    totalSessions: 180,
    teachingStyle: 'Project-based and practical. Students learn by building real applications while understanding the theory behind algorithms and data structures.',
    verified: true,
    joinedAt: '2023-08-15',
  },
  {
    id: 't6',
    clerkId: 'clerk_t6',
    name: 'Mei Ling Wong',
    email: 'meiling@edu.sg',
    avatar: tutorAvatars[5],
    bio: 'Dedicated Biology tutor who makes learning about life sciences fascinating. Specializing in O-Level and A-Level Biology with a focus on exam preparation.',
    qualifications: ['NUS BSc Life Sciences (Honours)', 'NIE PGDE', '7 Years Experience'],
    subjects: [
      { name: 'Biology', level: 'O-Level' },
      { name: 'Biology', level: 'A-Level' },
    ],
    hourlyRate: 58,
    rating: 4.6,
    totalReviews: 73,
    totalSessions: 195,
    teachingStyle: 'Visual and story-driven. I use diagrams, flowcharts, and real case studies to make biology concepts memorable and easy to recall during exams.',
    verified: true,
    joinedAt: '2023-05-22',
  },
  {
    id: 't7',
    clerkId: 'clerk_t7',
    name: 'Rajesh Kumar',
    email: 'rajesh.k@edu.sg',
    avatar: tutorAvatars[6],
    bio: 'Economics tutor with real-world finance experience. I help students understand economic theories through current events and Singapore economic context.',
    qualifications: ['NUS BBA (Honours)', 'CFA Level 2', '5 Years Tutoring Experience'],
    subjects: [
      { name: 'Economics', level: 'A-Level' },
      { name: 'Principles of Accounting', level: 'O-Level' },
    ],
    hourlyRate: 62,
    rating: 4.7,
    totalReviews: 56,
    totalSessions: 145,
    teachingStyle: 'Case-study driven with lots of real-world examples from Singapore and global markets. Strong focus on essay structuring and evaluation skills.',
    verified: true,
    joinedAt: '2023-09-01',
  },
  {
    id: 't8',
    clerkId: 'clerk_t8',
    name: 'Lily Chua',
    email: 'lily.chua@edu.sg',
    avatar: tutorAvatars[7],
    bio: 'Chinese Language specialist with over 15 years of teaching experience. Expert in Higher Chinese for O-Level and A-Level Chinese Language & Literature.',
    qualifications: ['Beijing Normal University BA Chinese', 'NIE PGDE', '15 Years MOE Experience'],
    subjects: [
      { name: 'Chinese Language', level: 'O-Level' },
      { name: 'Higher Chinese', level: 'O-Level' },
      { name: 'Chinese Language & Literature', level: 'A-Level' },
    ],
    hourlyRate: 50,
    rating: 4.8,
    totalReviews: 91,
    totalSessions: 320,
    teachingStyle: 'Immersive and culturally rich. Lessons incorporate Chinese literature, idioms, and current affairs to build comprehensive language skills.',
    verified: true,
    joinedAt: '2022-11-10',
  },
]

export const mockSessions: Session[] = [
  {
    id: 's1',
    tutorId: 't1',
    tutorName: 'James Tan',
    tutorAvatar: tutorAvatars[0],
    studentId: 'stu1',
    studentName: 'Alex Ng',
    studentAvatar: studentAvatars[0],
    subject: 'Mathematics',
    level: 'A-Level',
    date: '2026-03-05',
    startTime: '14:00',
    endTime: '15:30',
    duration: 90,
    status: 'booked',
    price: 97.5,
    meetingLink: 'https://meet.google.com/abc-defg-hij',
    notes: 'Focus on Integration techniques and past year papers',
  },
  {
    id: 's2',
    tutorId: 't2',
    tutorName: 'Sarah Lim',
    tutorAvatar: tutorAvatars[1],
    studentId: 'stu1',
    studentName: 'Alex Ng',
    studentAvatar: studentAvatars[0],
    subject: 'Chemistry',
    level: 'A-Level',
    date: '2026-03-07',
    startTime: '10:00',
    endTime: '11:30',
    duration: 90,
    status: 'booked',
    price: 105,
    meetingLink: 'https://meet.google.com/klm-nopq-rst',
    notes: 'Organic Chemistry mechanisms review',
  },
  {
    id: 's3',
    tutorId: 't4',
    tutorName: 'Priya Sharma',
    tutorAvatar: tutorAvatars[3],
    studentId: 'stu1',
    studentName: 'Alex Ng',
    studentAvatar: studentAvatars[0],
    subject: 'General Paper',
    level: 'A-Level',
    date: '2026-02-25',
    startTime: '16:00',
    endTime: '17:30',
    duration: 90,
    status: 'completed',
    price: 82.5,
    meetingLink: '',
    notes: 'Essay writing techniques for argumentative essays',
  },
  {
    id: 's4',
    tutorId: 't3',
    tutorName: 'Wei Ming Chen',
    tutorAvatar: tutorAvatars[2],
    studentId: 'stu1',
    studentName: 'Alex Ng',
    studentAvatar: studentAvatars[0],
    subject: 'Physics',
    level: 'A-Level',
    date: '2026-02-20',
    startTime: '09:00',
    endTime: '10:30',
    duration: 90,
    status: 'completed',
    price: 90,
    meetingLink: '',
    notes: 'Waves and Optics revision',
  },
  {
    id: 's5',
    tutorId: 't1',
    tutorName: 'James Tan',
    tutorAvatar: tutorAvatars[0],
    studentId: 'stu2',
    studentName: 'Bella Koh',
    studentAvatar: studentAvatars[1],
    subject: 'Mathematics',
    level: 'O-Level',
    date: '2026-03-06',
    startTime: '11:00',
    endTime: '12:00',
    duration: 60,
    status: 'booked',
    price: 65,
    meetingLink: 'https://meet.google.com/uvw-xyza-bcd',
    notes: 'Trigonometry and coordinate geometry',
  },
  {
    id: 's6',
    tutorId: 't5',
    tutorName: 'Ahmad Razak',
    tutorAvatar: tutorAvatars[4],
    studentId: 'stu1',
    studentName: 'Alex Ng',
    studentAvatar: studentAvatars[0],
    subject: 'Computing',
    level: 'A-Level',
    date: '2026-03-10',
    startTime: '15:00',
    endTime: '16:30',
    duration: 90,
    status: 'available',
    price: 112.5,
    meetingLink: '',
    notes: '',
  },
  {
    id: 's7',
    tutorId: 't2',
    tutorName: 'Sarah Lim',
    tutorAvatar: tutorAvatars[1],
    studentId: '',
    studentName: '',
    studentAvatar: '',
    subject: 'Chemistry',
    level: 'O-Level',
    date: '2026-03-08',
    startTime: '14:00',
    endTime: '15:00',
    duration: 60,
    status: 'available',
    price: 70,
    meetingLink: '',
    notes: '',
  },
  {
    id: 's8',
    tutorId: 't1',
    tutorName: 'James Tan',
    tutorAvatar: tutorAvatars[0],
    studentId: 'stu1',
    studentName: 'Alex Ng',
    studentAvatar: studentAvatars[0],
    subject: 'Mathematics',
    level: 'A-Level',
    date: '2026-02-15',
    startTime: '14:00',
    endTime: '15:30',
    duration: 90,
    status: 'completed',
    price: 97.5,
    meetingLink: '',
    notes: 'Differentiation and applications',
  },
  {
    id: 's9',
    tutorId: 't6',
    tutorName: 'Mei Ling Wong',
    tutorAvatar: tutorAvatars[5],
    studentId: 'stu1',
    studentName: 'Alex Ng',
    studentAvatar: studentAvatars[0],
    subject: 'Biology',
    level: 'A-Level',
    date: '2026-02-18',
    startTime: '10:00',
    endTime: '11:30',
    duration: 90,
    status: 'cancelled',
    price: 87,
    meetingLink: '',
    notes: 'Cell biology and genetics',
  },
]

export const mockReviews: Review[] = [
  {
    id: 'r1',
    sessionId: 's3',
    studentId: 'stu1',
    studentName: 'Alex Ng',
    studentAvatar: studentAvatars[0],
    tutorId: 't4',
    tutorName: 'Priya Sharma',
    rating: 5,
    comment: 'Priya is an amazing GP tutor! She helped me structure my arguments much better and gave really insightful feedback on my essay. My grades improved from C to A in just 3 months.',
    createdAt: '2026-02-26',
    subject: 'General Paper',
  },
  {
    id: 'r2',
    sessionId: 's4',
    studentId: 'stu1',
    studentName: 'Alex Ng',
    studentAvatar: studentAvatars[0],
    tutorId: 't3',
    tutorName: 'Wei Ming Chen',
    rating: 4,
    comment: 'Great physics lesson! Wei Ming explains concepts very clearly with real-world examples. The only suggestion is to provide more practice problems during the session.',
    createdAt: '2026-02-21',
    subject: 'Physics',
  },
  {
    id: 'r3',
    sessionId: 's8',
    studentId: 'stu1',
    studentName: 'Alex Ng',
    studentAvatar: studentAvatars[0],
    tutorId: 't1',
    tutorName: 'James Tan',
    rating: 5,
    comment: 'Mr Tan is hands down the best Math tutor I have had. His structured approach and step-by-step problem solving techniques are extremely effective. Highly recommend!',
    createdAt: '2026-02-16',
    subject: 'Mathematics',
  },
  {
    id: 'r4',
    sessionId: 's10',
    studentId: 'stu2',
    studentName: 'Bella Koh',
    studentAvatar: studentAvatars[1],
    tutorId: 't1',
    tutorName: 'James Tan',
    rating: 5,
    comment: 'Very patient and explains math concepts in a way that is easy to understand. My O-Level math improved from B4 to A1!',
    createdAt: '2026-02-10',
    subject: 'Mathematics',
  },
  {
    id: 'r5',
    sessionId: 's11',
    studentId: 'stu3',
    studentName: 'Chen Wei',
    studentAvatar: studentAvatars[2],
    tutorId: 't2',
    tutorName: 'Sarah Lim',
    rating: 5,
    comment: 'Sarah makes chemistry so interesting! Her use of animations and models really helped me visualize organic chemistry mechanisms. Could not recommend her more.',
    createdAt: '2026-02-08',
    subject: 'Chemistry',
  },
  {
    id: 'r6',
    sessionId: 's12',
    studentId: 'stu4',
    studentName: 'Devi Nair',
    studentAvatar: studentAvatars[3],
    tutorId: 't5',
    tutorName: 'Ahmad Razak',
    rating: 4,
    comment: 'Ahmad is a fantastic computing tutor. He explains algorithms using practical examples and helped me build my first Python project. Very inspiring teacher.',
    createdAt: '2026-01-28',
    subject: 'Computing',
  },
  {
    id: 'r7',
    sessionId: 's13',
    studentId: 'stu2',
    studentName: 'Bella Koh',
    studentAvatar: studentAvatars[1],
    tutorId: 't8',
    tutorName: 'Lily Chua',
    rating: 5,
    comment: 'Lily Laoshi is amazing! She makes Chinese lessons engaging with cultural stories and her teaching method helped me appreciate the language much more. My Higher Chinese grade jumped from B3 to A2.',
    createdAt: '2026-01-20',
    subject: 'Higher Chinese',
  },
  {
    id: 'r8',
    sessionId: 's14',
    studentId: 'stu3',
    studentName: 'Chen Wei',
    studentAvatar: studentAvatars[2],
    tutorId: 't7',
    tutorName: 'Rajesh Kumar',
    rating: 4,
    comment: 'Rajesh is very knowledgeable about economics and uses excellent real-world examples from Singapore. His essay structuring tips were particularly helpful for A-Level Econs.',
    createdAt: '2026-01-15',
    subject: 'Economics',
  },
]

export function getTutorById(id: string): Tutor | undefined {
  return mockTutors.find((t) => t.id === id)
}

export function getSessionsByStudentId(studentId: string): Session[] {
  return mockSessions.filter((s) => s.studentId === studentId)
}

export function getSessionsByTutorId(tutorId: string): Session[] {
  return mockSessions.filter((s) => s.tutorId === tutorId)
}

export function getReviewsByTutorId(tutorId: string): Review[] {
  return mockReviews.filter((r) => r.tutorId === tutorId)
}

export function getAvailableSessionsByTutorId(tutorId: string): Session[] {
  return mockSessions.filter((s) => s.tutorId === tutorId && s.status === 'available')
}
